Repository Discord4J/discord-json, pull requests merged in 2021-06, with the labels that each got.

#87 Make build successful on JDK 8
  build.gradle
  encoding/build.gradle
Labels: enhancement

#96 StatusUpdate#activities() is not nullable
  src/main/java/discord4j/discordjson/json/gateway/StatusUpdate.java
Labels: field/type-change

#97 Changed type of ApplicationCommandOptionChoiceData#value from String to Object
  src/main/java/discord4j/discordjson/json/ApplicationCommandOptionChoiceData.java
Labels: bug, field/type-change

#95 Reintroduce #93 but deprecate old overloads
  encoding/src/main/java/discord4j/discordjson/MetaEncodingEnabled.java
  encoding/src/main/java/discord4j/discordjson/possible/PossibleListEncoding.java
  encoding/src/main/java/discord4j/discordjson/possible/PossibleOptionalEncoding.java
  encoding/src/main/java/discord4j/discordjson/possible/PossibleOptionalIdEncoding.java
  encoding/src/main/java/discord4j/discordjson/possible/PossibleOptionalListEncoding.java
  src/test/java/discord4j/discordjson/PossibleDeserializerTest.java
Labels: enhancement
