Repository Discord4J/discord-json, pull requests merged in 2021-04, with the labels that each got.

#53 Adds interaction.application_id
  src/main/java/discord4j/discordjson/json/InteractionData.java
  src/test/resources/gateway/InteractionCreate.SubCommandGroup.json
  src/test/resources/gateway/InteractionCreate.json
Labels: field/addition

#55 Adds Stage channel
  src/main/java/discord4j/discordjson/json/UpdateOthersVoiceStateRequest.java
  src/main/java/discord4j/discordjson/json/UpdateSelfVoiceStateRequest.java
  src/main/java/discord4j/discordjson/json/VoiceStateData.java
  src/test/resources/gateway/VoiceStateUpdate.json
Labels: class/addition, field/addition

#54 Adds interactions resolved objects
  src/main/java/discord4j/discordjson/json/ApplicationCommandInteractionData.java
  src/main/java/discord4j/discordjson/json/ApplicationCommandInteractionResolvedData.java
  src/main/java/discord4j/discordjson/json/ResolvedChannelData.java
  src/main/java/discord4j/discordjson/json/ResolvedMemberData.java
Labels: class/addition, field/addition

#56 Adds Integration events
  src/main/java/discord4j/discordjson/json/IntegrationData.java
  src/main/java/discord4j/discordjson/json/gateway/IntegrationCreate.java
  src/main/java/discord4j/discordjson/json/gateway/IntegrationDelete.java
  src/main/java/discord4j/discordjson/json/gateway/IntegrationUpdate.java
  src/test/java/discord4j/discordjson/json/gateway/GatewayDeserializationTest.java
  src/test/java/discord4j/discordjson/json/gateway/PayloadDeserializer.java
  src/test/resources/gateway/IntegrationCreate.json
  src/test/resources/gateway/IntegrationDelete.json
  src/test/resources/gateway/IntegrationUpdate.json
Labels: class/addition, field/type-change

#57 Adds WelcomeScreen
  src/main/java/discord4j/discordjson/json/GuildFields.java
  src/main/java/discord4j/discordjson/json/GuildWelcomeScreenModifyRequest.java
  src/main/java/discord4j/discordjson/json/WelcomeScreenChannelData.java
  src/main/java/discord4j/discordjson/json/WelcomeScreenData.java
  src/test/java/discord4j/discordjson/json/rest/RestDeserializationTest.java
  src/test/resources/rest/WelcomeScreen.json
Labels: class/addition, field/addition

#58 Attachment dimensions are optional
  src/main/java/discord4j/discordjson/json/AttachmentData.java
Labels: field/type-change

#60 Updates Invite
  src/main/java/discord4j/discordjson/json/InviteCreateRequest.java
  src/main/java/discord4j/discordjson/json/InviteData.java
  src/main/java/discord4j/discordjson/json/gateway/InviteCreate.java
  src/test/resources/gateway/InviteCreate.json
  src/test/resources/rest/ChannelInvites.json
Labels: field/addition, field/removal, field/type-change

#61 Updates Webhook
  src/main/java/discord4j/discordjson/json/WebhookData.java
  src/main/java/discord4j/discordjson/json/WebhookPartialChannelData.java
  src/main/java/discord4j/discordjson/json/WebhookPartialGuildData.java
Labels: class/addition, field/addition

#62 Updates position modify request
  src/main/java/discord4j/discordjson/json/PositionModifyRequest.java
Labels: field/addition

#63 AuditLogEntry#user_id is nullable
  src/main/java/discord4j/discordjson/json/AuditLogEntryData.java
Labels: field/type-change

#64 Updates GuildModifyRequest
  src/main/java/discord4j/discordjson/json/GuildModifyRequest.java
Labels: field/addition, field/type-change

#65 Updates MessageReference
  src/main/java/discord4j/discordjson/json/MessageReferenceData.java
Labels: field/addition

#67 Add Attachement#content_type
  src/main/java/discord4j/discordjson/json/AttachmentData.java
Labels: field/addition

#68 Updates VoiceChannel fields
  src/main/java/discord4j/discordjson/json/ChannelData.java
  src/main/java/discord4j/discordjson/json/ChannelModifyRequest.java
  src/test/resources/gateway/GuildCreate.json
  src/test/resources/rest/TemplateData.json
Labels: field/addition

#69 Update ApplicationInfoData fields
  src/main/java/discord4j/discordjson/json/ApplicationInfoData.java
Labels: field/addition

#70 Update Stage Channels Requests name
  src/main/java/discord4j/discordjson/json/UpdateCurrentUserVoiceStateRequest.java
  src/main/java/discord4j/discordjson/json/UpdateUserVoiceStateRequest.java
Labels: class/rename

#71 Updates Application Command permissions
  src/main/java/discord4j/discordjson/json/ApplicationCommandRequest.java
  src/main/java/discord4j/discordjson/json/GuildApplicationCommandPermissionsData.java
  src/main/java/discord4j/discordjson/json/PartialGuildApplicationCommandPermissionsData.java
Labels: class/addition, field/addition

#72 Address TODOs
  src/main/java/discord4j/discordjson/json/EmbedProviderData.java
  src/main/java/discord4j/discordjson/json/GuildFields.java
  src/main/java/discord4j/discordjson/json/GuildUpdateFields.java
  src/test/java/discord4j/discordjson/DataMappingTest.java
Labels: discord issue, field/type-change

#59 Removes guild_subscriptions field
  src/main/java/discord4j/discordjson/json/gateway/Identify.java
  src/test/java/discord4j/discordjson/json/gateway/GatewaySerializationTest.java
  src/test/resources/gateway/outbound/Identify.json
Labels: field/removal

#75 Create ApplicationCommandPermissionsRequest
  src/main/java/discord4j/discordjson/json/ApplicationCommandPermissionsRequest.java
Labels: class/addition

#76 Audit log changes
  src/main/java/discord4j/discordjson/json/AuditLogChangeData.java
  src/main/java/discord4j/discordjson/json/AuditLogPartialRoleData.java
Labels: class/addition, field/type-change

#73 Adds Guild#nsfw field
  src/main/java/discord4j/discordjson/json/GuildFields.java
  src/test/resources/gateway/GuildCreate.json
  src/test/resources/gateway/GuildUpdate.json
  src/test/resources/rest/Guild.json
Labels: field/addition

#74 Remove MessageSticker#preview_asset
  src/main/java/discord4j/discordjson/json/StickerData.java
Labels: field/removal
