Repository Discord4J/discord-json, pull requests merged in 2021-05, with the labels that each got.

#77 Add OAuth2 JSON objects
  src/main/java/discord4j/discordjson/json/AccessTokenData.java
  src/main/java/discord4j/discordjson/json/AuthorizationCodeGrantRequest.java
  src/main/java/discord4j/discordjson/json/AuthorizationInfoData.java
  src/main/java/discord4j/discordjson/json/ClientCredentialsGrantRequest.java
  src/main/java/discord4j/discordjson/json/TokenRefreshRequest.java
  src/main/java/discord4j/discordjson/json/TokenRevokeRequest.java
Labels: class/addition

#78 Adds MessageEditRequest#attachments
  src/main/java/discord4j/discordjson/json/AttachmentData.java
  src/main/java/discord4j/discordjson/json/MessageEditRequest.java
Labels: field/addition, field/type-change

#79 Adds WebhookMessageEditRequest#attachments
  src/main/java/discord4j/discordjson/json/WebhookMessageEditRequest.java
Labels: field/addition

#80 Add InviteData#expires_at
  src/main/java/discord4j/discordjson/json/InviteData.java
Labels: field/addition

#81 Add Message#application_id
  src/main/java/discord4j/discordjson/json/MessageData.java
Labels: field/addition

#82 Add Team#name
  src/main/java/discord4j/discordjson/json/ApplicationTeamData.java
Labels: field/addition

#85 Create FollowupMessageRequest
  src/main/java/discord4j/discordjson/json/FollowupMessageRequest.java
Labels: class/addition

#83 Guild member joined at can be null
  src/main/java/discord4j/discordjson/json/gateway/GuildMemberUpdate.java
Labels: field/type-change

#84 Update WebhookData guildId and channelId
  src/main/java/discord4j/discordjson/json/WebhookData.java
  src/test/java/discord4j/discordjson/json/rest/RestDeserializationTest.java
  src/test/resources/rest/ApplicationWebhook.json
  src/test/resources/rest/ChannelFollowedWebhook.json
Labels: field/type-change

#88 Add GuildFields#nsfw_level
  src/main/java/discord4j/discordjson/json/GuildFields.java
  src/test/java/discord4j/discordjson/DataMappingTest.java
  src/test/resources/gateway/GuildCreate.json
  src/test/resources/gateway/GuildUpdate.json
  src/test/resources/rest/ChannelInvites.json
  src/test/resources/rest/Guild.json
  src/test/resources/rest/UserGuildData.json
Labels: field/addition

#89 Create Webhook avatar is optional
  src/main/java/discord4j/discordjson/json/WebhookCreateRequest.java
Labels: field/type-change

#91 Member#joinedAt is nullable
  src/main/java/discord4j/discordjson/json/MemberData.java
Labels: field/type-change

#92 Assign default value to Possible encodings
  encoding/src/main/java/discord4j/discordjson/OptionalIdEncoding.java
  encoding/src/main/java/discord4j/discordjson/possible/PossibleEncoding.java
  encoding/src/main/java/discord4j/discordjson/possible/PossibleIdEncoding.java
  encoding/src/main/java/discord4j/discordjson/possible/PossibleIntArrayEncoding.java
  encoding/src/main/java/discord4j/discordjson/possible/PossibleListEncoding.java
  encoding/src/main/java/discord4j/discordjson/possible/PossibleOptionalEncoding.java
  encoding/src/main/java/discord4j/discordjson/possible/PossibleOptionalIdEncoding.java
Labels: enhancement

#93 Various enhancements for the Encoding module
  encoding/src/main/java/discord4j/discordjson/MetaEncodingEnabled.java
  encoding/src/main/java/discord4j/discordjson/possible/PossibleListEncoding.java
  encoding/src/main/java/discord4j/discordjson/possible/PossibleOptionalEncoding.java
  encoding/src/main/java/discord4j/discordjson/possible/PossibleOptionalIdEncoding.java
  encoding/src/main/java/discord4j/discordjson/possible/PossibleOptionalListEncoding.java
  src/test/java/discord4j/discordjson/PossibleDeserializerTest.java
Labels: enhancement
