Repository Discord4J/discord-json, pull requests merged in 2022-01, with the labels that each got.

#113 Add support for timeout (communication_disabled_until)
  src/main/java/discord4j/discordjson/json/GuildMemberModifyRequest.java
  src/main/java/discord4j/discordjson/json/PartialMemberData.java
  src/main/java/discord4j/discordjson/json/ResolvedMemberData.java
  src/main/java/discord4j/discordjson/json/gateway/GuildMemberUpdate.java
Labels: enhancement, field/addition

#106 Changed ThreadMemberData#id() and userId() to Possible
  src/main/java/discord4j/discordjson/json/ThreadMemberData.java
Labels: field/type-change

#112 Add support for Guild Scheduled Events
  src/main/java/discord4j/discordjson/json/GuildScheduledEventCreateRequest.java
  src/main/java/discord4j/discordjson/json/GuildScheduledEventData.java
  src/main/java/discord4j/discordjson/json/GuildScheduledEventEntityMetadataData.java
  src/main/java/discord4j/discordjson/json/GuildScheduledEventModifyRequest.java
  src/main/java/discord4j/discordjson/json/GuildScheduledEventUserData.java
  src/main/java/discord4j/discordjson/json/InviteData.java
  src/main/java/discord4j/discordjson/json/gateway/GuildScheduledEventCreate.java
  src/main/java/discord4j/discordjson/json/gateway/GuildScheduledEventDelete.java
  src/main/java/discord4j/discordjson/json/gateway/GuildScheduledEventUpdate.java
  src/main/java/discord4j/discordjson/json/gateway/GuildScheduledEventUserAdd.java
  src/main/java/discord4j/discordjson/json/gateway/GuildScheduledEventUserRemove.java
Labels: enhancement, field/addition, class/addition
