Repository Discord4J/discord-json, pull requests merged in 2023-04, with the labels that each got.

#140 Add forum missing fields in channel related requests
  src/main/java/discord4j/discordjson/json/ChannelCreateRequest.java
  src/main/java/discord4j/discordjson/json/ChannelModifyRequest.java
  src/main/java/discord4j/discordjson/json/ForumTagParamsData.java
Labels: field/addition

#142 Add partial channel to InteractionData
  src/main/java/discord4j/discordjson/json/InteractionData.java
Labels: field/addition

#141 Implement structure for Onboarding data
  src/main/java/discord4j/discordjson/json/OnboardingData.java
  src/main/java/discord4j/discordjson/json/OnboardingPromptData.java
  src/main/java/discord4j/discordjson/json/OnboardingPromptOptionData.java
  src/test/java/discord4j/discordjson/json/rest/RestDeserializationTest.java
  src/test/resources/rest/GuildOnboardingDataResponse.json
Labels: class/addition

#143 Fix missing JsonProperty annotation in guild event create request
  src/main/java/discord4j/discordjson/json/GuildScheduledEventCreateRequest.java
Labels: bug
