Repository Discord4J/discord-json, pull requests merged in 2023-02, with the labels that each got.

#135 Add Flags field to Guild Member data
  src/main/java/discord4j/discordjson/json/PartialMemberData.java
  src/main/java/discord4j/discordjson/json/ResolvedMemberData.java
  src/test/resources/gateway/GuildCreate.json
  src/test/resources/gateway/GuildMemberAdd.json
  src/test/resources/gateway/GuildMembersChunk.Presences.json
  src/test/resources/gateway/GuildMembersChunk.json
  src/test/resources/gateway/InteractionCreate.SubCommandGroup.json
  src/test/resources/gateway/InteractionCreate.json
  src/test/resources/gateway/MessageCreate.Type0.json
  src/test/resources/gateway/MessageCreate.Type19.json
  src/test/resources/gateway/MessageCreate.Type6.json
Labels: field/addition

#136 Added Discord Application Command Permissions Update Event
  src/main/java/discord4j/discordjson/json/gateway/ApplicationCommandPermissionUpdate.java
Labels: class/addition

#138 Add custom_message field to AutoModActionMetaData
  src/main/java/discord4j/discordjson/json/AutoModActionMetaData.java
Labels: field/addition

#133 Add support for guild forum related objects (3.3.x only)
  src/main/java/discord4j/discordjson/json/ChannelData.java
  src/main/java/discord4j/discordjson/json/DefaultReactionData.java
  src/main/java/discord4j/discordjson/json/ForumTagData.java
  src/main/java/discord4j/discordjson/json/ForumThreadCreateRequest.java
  src/main/java/discord4j/discordjson/json/ForumThreadMessageParamsData.java
Labels: field/addition, class/addition

#134 Add missing field in gateway event ThreadCreate
  src/main/java/discord4j/discordjson/json/gateway/ThreadCreate.java
  src/main/java/discord4j/discordjson/json/gateway/ThreadMembersUpdate.java
Labels: field/addition, field/type-change
