Repository Discord4J/discord-json, pull requests merged in 2024-06, with the labels that each got.

#170 feat: add EntitlementData#consumed
  src/main/java/discord4j/discordjson/json/EntitlementData.java
Labels: field/addition

#166 Bulk Ban Request Support
  src/main/java/discord4j/discordjson/json/BulkBanRequest.java
  src/main/java/discord4j/discordjson/json/BulkBanResponseData.java
Labels: enhancement, class/addition

#173 feat: add support for "applied_tags" field for ChannelCreateRequest, ChannelModifyRequest and WebhookExecuteRequest
  src/main/java/discord4j/discordjson/json/ChannelCreateRequest.java
  src/main/java/discord4j/discordjson/json/ChannelModifyRequest.java
  src/main/java/discord4j/discordjson/json/ForumThreadMessageParamsData.java
  src/main/java/discord4j/discordjson/json/StartThreadFromMessageRequest.java
  src/main/java/discord4j/discordjson/json/ThreadModifyRequest.java
  src/main/java/discord4j/discordjson/json/WebhookExecuteRequest.java
Labels: field/addition

#172 Dependency/package updates
  api/src/main/java/discord4j/discordjson/possible/Possible.java
  api/src/main/java/discord4j/discordjson/possible/PossibleDeserializer.java
  api/src/main/java/discord4j/discordjson/possible/PossibleDeserializers.java
  api/src/main/java/discord4j/discordjson/possible/PossibleFilter.java
  api/src/main/java/discord4j/discordjson/possible/PossibleSerializer.java
  api/src/main/java/discord4j/discordjson/possible/PossibleSerializers.java
  api/src/main/java/discord4j/discordjson/possible/package-info.java
  build.gradle
  encoding/src/main/java/discord4j/discordjson/encoding/IdEncoding.java
  encoding/src/main/java/discord4j/discordjson/encoding/ListIdEncoding.java
  encoding/src/main/java/discord4j/discordjson/encoding/MetaEncodingEnabled.java
  encoding/src/main/java/discord4j/discordjson/encoding/OptionalIdEncoding.java
  encoding/src/main/java/discord4j/discordjson/encoding/possible/PossibleEncoding.java
  encoding/src/main/java/discord4j/discordjson/encoding/possible/PossibleIdEncoding.java
  encoding/src/main/java/discord4j/discordjson/encoding/possible/PossibleIntArrayEncoding.java
  encoding/src/main/java/discord4j/discordjson/encoding/possible/PossibleListEncoding.java
  encoding/src/main/java/discord4j/discordjson/encoding/possible/PossibleOptionalEncoding.java
  encoding/src/main/java/discord4j/discordjson/encoding/possible/PossibleOptionalIdEncoding.java
  encoding/src/main/java/discord4j/discordjson/encoding/possible/PossibleOptionalListEncoding.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/discord4j/discordjson/json/GuildCreateRequest.java
  src/main/java/discord4j/discordjson/json/gateway/Opcode.java
  src/main/java/discord4j/discordjson/json/gateway/VoiceServerUpdate.java
  src/main/java/discord4j/discordjson/json/gateway/package-info.java
  src/main/java/discord4j/discordjson/json/package-info.java
  src/test/java/discord4j/discordjson/json/gateway/GatewayPayload.java
  src/test/java/discord4j/discordjson/json/gateway/PayloadDeserializer.java
  src/test/java/discord4j/discordjson/json/id/package-info.java
  src/test/java/discord4j/discordjson/json/package-info.java
Labels: enhancement

#175 feat: add missing WebhookExecuteRequest#threadName and threadId
  src/main/java/discord4j/discordjson/json/WebhookExecuteRequest.java
Labels: field/addition

#164 feat: add polls support
  api/src/main/java/discord4j/discordjson/possible/Possible.java
  src/main/java/discord4j/discordjson/json/MessageData.java
  src/main/java/discord4j/discordjson/json/MessageSendRequestBase.java
  src/main/java/discord4j/discordjson/json/PollAnswerCountObject.java
  src/main/java/discord4j/discordjson/json/PollAnswerObject.java
  src/main/java/discord4j/discordjson/json/PollCreateData.java
  src/main/java/discord4j/discordjson/json/PollData.java
  src/main/java/discord4j/discordjson/json/PollMediaObject.java
  src/main/java/discord4j/discordjson/json/PollResultObject.java
  src/main/java/discord4j/discordjson/json/gateway/MessagePollVoteAdd.java
  src/main/java/discord4j/discordjson/json/gateway/MessagePollVoteRemove.java
  src/main/java/discord4j/discordjson/json/gateway/PollVoteAdd.java
  src/main/java/discord4j/discordjson/json/gateway/PollVoteRemove.java
  src/main/java/discord4j/discordjson/json/gateway/PollVoters.java
Labels: enhancement, field/addition, class/addition

#178 feat: Add support for the `enforce_nonce` parameter on message creation
  src/main/java/discord4j/discordjson/json/MessageCreateRequest.java
Labels: field/addition

#174 fix: onboarding
  src/main/java/discord4j/discordjson/json/BaseOnboardingData.java
  src/main/java/discord4j/discordjson/json/BaseOnboardingPromptData.java
  src/main/java/discord4j/discordjson/json/BaseOnboardingPromptOptionData.java
  src/main/java/discord4j/discordjson/json/OnboardingData.java
  src/main/java/discord4j/discordjson/json/OnboardingEditData.java
  src/main/java/discord4j/discordjson/json/OnboardingEditPromptData.java
  src/main/java/discord4j/discordjson/json/OnboardingEditPromptOptionData.java
  src/main/java/discord4j/discordjson/json/OnboardingPromptData.java
  src/main/java/discord4j/discordjson/json/OnboardingPromptOptionData.java
  src/test/resources/rest/GuildOnboardingDataResponse.json
Labels: field/addition, field/type-change, class/addition

#179 feat: add missing fields in ApplicationInfo
  api/src/main/java/discord4j/discordjson/annotation/Experimental.java
  src/main/java/discord4j/discordjson/json/ApplicationInfoData.java
  src/main/java/discord4j/discordjson/json/ApplicationInstallParamsData.java
  src/main/java/discord4j/discordjson/json/ApplicationIntegrationTypeConfigurationData.java
  src/main/java/discord4j/discordjson/json/ApplicationTeamMemberData.java
  src/test/java/discord4j/discordjson/json/rest/RestDeserializationTest.java
  src/test/resources/rest/ApplicationInfoData.json
Labels: field/addition, field/type-change, class/addition

#181 feat: add support for Application Role Connection Metadata
  src/main/java/discord4j/discordjson/json/ApplicationRoleConnectionMetadataData.java
  src/main/java/discord4j/discordjson/json/RoleTagsData.java
Labels: field/addition, class/addition

#182 feat: add support for the new premium button style
  src/main/java/discord4j/discordjson/json/ComponentData.java
Labels: field/addition

#177 Add avatar decoration fields
  src/main/java/discord4j/discordjson/json/AvatarDecorationData.java
  src/main/java/discord4j/discordjson/json/PartialMemberData.java
  src/main/java/discord4j/discordjson/json/ResolvedMemberData.java
  src/main/java/discord4j/discordjson/json/UserData.java
  src/main/java/discord4j/discordjson/json/gateway/GuildMemberUpdate.java
Labels: field/addition, class/addition

#180 fix: split PositionModifyRequest to ChannelPositionModifyRequest and RolePositionModifyRequest
  src/main/java/discord4j/discordjson/json/ChannelPositionModifyRequest.java
  src/main/java/discord4j/discordjson/json/RolePositionModifyRequest.java
Labels: field/type-change, class/addition, class/rename
