Repository Discord4J/discord-json, pull requests merged in 2024-03, with the labels that each got.

#161 Update resolved data structure in application command interactions
  src/main/java/discord4j/discordjson/json/ResolvedChannelData.java
  src/main/java/discord4j/discordjson/json/ResolvedMemberData.java
Labels: field/addition, field/type-change

#155 Implement SuperReactions (Burst) data
  src/main/java/discord4j/discordjson/json/ReactionCountDetailsData.java
  src/main/java/discord4j/discordjson/json/ReactionData.java
  src/test/java/discord4j/discordjson/json/rest/RestDeserializationTest.java
Labels: field/addition, class/addition

#158 Edit Current Application
  src/main/java/discord4j/discordjson/json/ApplicationInfoRequest.java
  src/main/java/discord4j/discordjson/json/InstallParamsData.java
Labels: class/addition

#160 feat: add monetization data classes
  src/main/java/discord4j/discordjson/json/CreateTestEntitlementRequest.java
  src/main/java/discord4j/discordjson/json/EntitlementData.java
  src/main/java/discord4j/discordjson/json/InteractionData.java
  src/main/java/discord4j/discordjson/json/SkuData.java
  src/main/java/discord4j/discordjson/json/gateway/EntitlementCreate.java
  src/main/java/discord4j/discordjson/json/gateway/EntitlementDelete.java
  src/main/java/discord4j/discordjson/json/gateway/EntitlementUpdate.java
Labels: enhancement, field/addition, class/addition

#162 feat: added fields related to user-installed applications
  src/main/java/discord4j/discordjson/json/ApplicationCommandData.java
  src/main/java/discord4j/discordjson/json/ApplicationCommandRequest.java
  src/main/java/discord4j/discordjson/json/InteractionData.java
Labels: field/addition, deprecation

#163 fix: added missing nsfw field for application command
  src/main/java/discord4j/discordjson/json/ApplicationCommandData.java
  src/main/java/discord4j/discordjson/json/ApplicationCommandRequest.java
Labels: field/addition
